// Multi-sidebar setup: ONE sidebar per course. A page only ever shows its own
// course's sidebar, which is what gives each course a standalone,
// Coursera-style feel. Add one entry per migrated course.
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  learnLikeATopPerformer: [{type: 'autogenerated', dirName: 'courses/learn-like-a-top-performer'}],
  pyspark: [{type: 'autogenerated', dirName: 'courses/pyspark'}],
  windowsSetup: [{type: 'autogenerated', dirName: 'courses/windows-setup'}],
  mysqlWorkbenchSetup: [{type: 'autogenerated', dirName: 'courses/mysql-workbench-setup'}],
  sqlForDataEngineering: [{type: 'autogenerated', dirName: 'courses/sql-for-data-engineering'}],
  gitGithubBasics: [{type: 'autogenerated', dirName: 'courses/git-github-basics'}],
  linuxBasics: [{type: 'autogenerated', dirName: 'courses/linux-basics'}],
  githubUltimate: [{type: 'autogenerated', dirName: 'courses/github-ultimate'}],
  pythonDataEngineering: [{type: 'autogenerated', dirName: 'courses/python-data-engineering'}],
  dataEngineeringOnAws: [{type: 'autogenerated', dirName: 'courses/data-engineering-on-aws'}],
  awsAnalyticsPart1: [{type: 'autogenerated', dirName: 'courses/aws-analytics-part1'}],
  awsAnalyticsPart2: [{type: 'autogenerated', dirName: 'courses/aws-analytics-part2'}],
  azureAnalyticsPart1: [{type: 'autogenerated', dirName: 'courses/azure-analytics-part1'}],
  azureAnalyticsPart2: [{type: 'autogenerated', dirName: 'courses/azure-analytics-part2'}],
  dataModelling: [{type: 'autogenerated', dirName: 'courses/data-modelling'}],
};
module.exports = sidebars;
