import Link from "next/link";
import { ArrowRight, Check, LockKeyhole, RotateCcw, ShieldCheck } from "lucide-react";

export function AuthPage({ signInHref, error = false }: { signInHref: string; error?: boolean }) {
  return <main id="main-content" className="auth-page auth-chatgpt-page">
    <section className="auth-brand-panel" aria-label="About AgentLab"><Link className="brand brand-inverse" href="/"><span className="brand-mark" aria-hidden="true">A</span><span>AgentLab</span></Link><div><span className="auth-icon"><ShieldCheck size={30} aria-hidden="true"/></span><h1>Learn agents<br/>by building agents.</h1><p>A HitaVirTech engineering environment for learning, building, debugging, evaluating and proving Agentic AI skills.</p><ul><li><Check size={18} aria-hidden="true"/> Learner records isolated by account</li><li><Check size={18} aria-hidden="true"/> Labs, missions and evidence saved</li><li><Check size={18} aria-hidden="true"/> Credentials validated server-side</li></ul></div><small>HitaVirTech · AgentLab AI Learning</small></section>
    <section className="auth-form-panel" aria-labelledby="auth-heading"><div className="auth-form-wrap"><Link className="back-link" href="/">← Back to AgentLab</Link><span className="auth-lock"><LockKeyhole size={24} aria-hidden="true"/></span><span className="eyebrow">SECURE SIGN IN</span><h2 id="auth-heading">Continue with ChatGPT</h2><p>Sign in to save your AgentPath, course progress, labs, missions, mastery evidence, projects and credentials.</p>{error && <div className="auth-error" role="alert"><strong>We couldn’t complete sign-in.</strong><p>Your learning data is safe. Try again, or return to the public product pages.</p></div>}<Link className="button auth-submit" href={signInHref}>{error ? <RotateCcw size={18} aria-hidden="true"/> : null}{error ? "Retry sign in" : "Sign in with ChatGPT"}<ArrowRight size={18} aria-hidden="true"/></Link><p className="auth-privacy">AgentLab never receives your password or authentication token. ChatGPT handles authentication and returns you to the exact protected page you requested.</p></div></section>
  </main>;
}
