"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Award, BookOpen, Check, ChevronDown, Clock, FileQuestion, FolderKanban, LockKeyhole, Target } from "lucide-react";
import { findCourse, findLessonExact, lessonHref, lessonsForCourse } from "../lib/course-data";
import { courseProjectsFor, projectStatus } from "../lib/course-projects";
import { Footer, Navbar } from "./navigation";
import { useProgress } from "./providers";
import { Pill, ProgressBar } from "./ui";

export function CoursePage({ slug }: { slug: string }) {
  const course = findCourse(slug);
  const { enrollCourse, enrollments, isComplete, lastLesson, minorProjectSubmissions, progressRecords, viewer } = useProgress();
  const lessons = lessonsForCourse(course.slug);
  const projects = courseProjectsFor(course);
  const completed = lessons.filter(({ unit, lesson }) => isComplete(course.id, unit.id, lesson.id));
  const completedKeys = new Set(completed.map(({ unit, lesson }) => `${course.id}/${unit.id}/${lesson.id}`));
  const projectStatuses = projects.map((project) => projectStatus(project, course, completedKeys, minorProjectSubmissions[project.slug]));
  const completedProjects = projectStatuses.filter((status) => status === "COMPLETED").length;
  const percentage = Math.min(100, Math.round((completed.length / lessons.length) * 80 + (completedProjects / projects.length) * 20));
  const courseComplete = completed.length === lessons.length && completedProjects === projects.length;
  const firstIncomplete = lessons.find(({ unit, lesson }) => !isComplete(course.id, unit.id, lesson.id)) ?? lessons[0];
  const remembered = lastLesson?.courseSlug === course.slug ? findLessonExact(course.slug, lastLesson.unitId, lastLesson.lessonId) : undefined;
  const resumeLesson = remembered && !isComplete(course.id, remembered.unit.id, remembered.lesson.id) ? remembered : firstIncomplete;
  const [openUnits, setOpenUnits] = useState<string[]>([firstIncomplete.unit.id]);
  const startHref = lessonHref(course.slug, resumeLesson.unit.id, resumeLesson.lesson.id);
  const primaryHref = viewer ? startHref : `/login?returnTo=${encodeURIComponent(startHref)}`;
  const started = Boolean(enrollments[course.id]) || progressRecords.some((record) => record.courseId === course.id);
  const primaryLabel = !viewer ? "Sign in to start" : courseComplete ? "Review course" : started ? "Continue learning" : "Start learning";
  const toggle = (id: string) => setOpenUnits((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);

  return <div className="site-page"><Navbar /><main id="main-content">
    <section className={`course-hero course-hero-${course.subject}`}><div className="section-shell course-hero-grid"><div><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/courses">Courses</Link><span aria-hidden="true">/</span><span aria-current="page">{course.shortTitle}</span></nav><Pill tone="green">{course.level.toUpperCase()} COURSE</Pill><h1>{course.title}</h1><p>{course.shortDescription}</p><div className="course-facts"><span><BookOpen size={19} aria-hidden="true" /> {course.units.length} modules</span><span><Clock size={19} aria-hidden="true" /> {course.duration}</span><span><FolderKanban size={19} aria-hidden="true" /> {projects.length} assigned projects</span><span><FileQuestion size={19} aria-hidden="true" /> Lessons and checks</span></div><div className="course-tags">{course.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><Link className="button" href={primaryHref} onClick={() => { if (viewer) enrollCourse(course.id); }}>{primaryLabel}<ArrowRight size={19} aria-hidden="true" /></Link></div><div className="course-summary-card"><span className="summary-icon"><Target size={30} aria-hidden="true" /></span><h2>Course outcome</h2><p>{course.subtitle}</p>{viewer && <><strong>{percentage}%</strong><ProgressBar value={percentage} label={`${completed.length} of ${lessons.length} lessons and ${completedProjects} of ${projects.length} projects completed`} /><p>{completed.length} of {lessons.length} lessons · {completedProjects} of {projects.length} projects</p></>}<div className="summary-list"><span><Check size={18} aria-hidden="true" /> Progress saves automatically</span><span><Check size={18} aria-hidden="true" /> Projects unlock after prerequisites</span><span><Check size={18} aria-hidden="true" /> Completion requires lessons and projects</span></div></div></div></section>
    <section className="course-overview section-shell" aria-label="Course overview"><article><span><Target size={22} aria-hidden="true" /></span><h2>What you’ll learn</h2><ul>{course.outcomes.map((item) => <li key={item}>{item}</li>)}</ul></article><article><span><BookOpen size={22} aria-hidden="true" /></span><h2>Before you start</h2><ul>{course.prerequisites.map((item) => <li key={item}>{item}</li>)}</ul></article></section>
    <section className="curriculum section-shell"><div className="curriculum-head"><div><div className="eyebrow">COURSE CURRICULUM</div><h2>{course.curriculumHeadline}</h2></div><p>Work through each module and lesson in order. Assigned projects appear after their prerequisite modules.</p></div><div className="curriculum-list">{course.units.map((unit, unitIndex) => { const open = openUnits.includes(unit.id); const done = unit.lessons.filter((lesson) => isComplete(course.id, unit.id, lesson.id)).length; const minutes = unit.lessons.reduce((sum, lesson) => sum + Number(lesson.duration.match(/\d+/)?.[0] || 0), 0); const project = projects.find((item) => item.insertAfterModule === unitIndex + 1); return <article className="unit-accordion" id={unit.id} key={unit.id}><button className="unit-button" onClick={() => toggle(unit.id)} aria-expanded={open} aria-controls={`${unit.id}-lessons`}><span className="unit-number">{String(unitIndex + 1).padStart(2, "0")}</span><span className="unit-label"><strong>Module {unitIndex + 1} · {unit.title}</strong><small>{unit.description}</small><span className="module-meta">{unit.lessons.length} lessons · about {Math.max(1, Math.round(minutes / 60))}h{project ? ` · Project ${project.position} follows` : ""}</span></span><span className={`unit-count ${done === unit.lessons.length ? "complete" : ""}`}>{done === unit.lessons.length ? "Completed" : `${done} of ${unit.lessons.length}`}</span><ChevronDown className={open ? "rotate" : ""} size={22} aria-hidden="true" /></button>{open && <div className="lesson-list" id={`${unit.id}-lessons`}>{unit.lessons.map((lesson, lessonIndex) => <Link className="lesson-row" href={viewer ? lessonHref(course.slug, unit.id, lesson.id) : `/login?returnTo=${encodeURIComponent(lessonHref(course.slug, unit.id, lesson.id))}`} key={lesson.id}><span className={`lesson-status ${isComplete(course.id, unit.id, lesson.id) ? "done" : ""}`}>{isComplete(course.id, unit.id, lesson.id) ? <Check size={16} aria-label="Completed" /> : lessonIndex + 1}</span><span className="lesson-row-title"><strong>{lesson.title}</strong><small>{lesson.type === "quiz" ? "Lesson check" : lesson.type === "project" ? "Assigned project lesson" : "Lesson"}</small></span><span className="lesson-duration"><Clock size={16} aria-hidden="true" />{lesson.duration}</span><ArrowRight size={18} aria-hidden="true" /></Link>)}</div>}</article>; })}</div></section>
    <CourseMilestones course={course} projects={projects} statuses={projectStatuses} viewer={Boolean(viewer)} />
    <section className="course-certification-card section-shell" aria-labelledby="course-certification-heading"><div className="course-certification-icon"><Award size={25} aria-hidden="true" /></div><div><span className="eyebrow">FINAL MILESTONE</span><h2 id="course-certification-heading">Certification</h2><p>Finish every lesson, pass every assessment, and complete both assigned projects. Eligibility is checked server-side at exactly 100%.</p></div><Link className="button button-secondary" href={viewer ? `/courses/${course.slug}/certification` : `/login?returnTo=${encodeURIComponent(`/courses/${course.slug}/certification`)}`}>View certification <ArrowRight size={17} aria-hidden="true" /></Link></section>
  </main><Footer /></div>;
}

function CourseMilestones({ course, projects, statuses, viewer }: { course: ReturnType<typeof findCourse>; projects: ReturnType<typeof courseProjectsFor>; statuses: string[]; viewer: boolean }) {
  return <section className="course-milestones section-shell" aria-labelledby="course-milestones-heading"><div className="course-projects-heading"><div><span className="eyebrow">LEARN → APPLY → CONTINUE</span><h2 id="course-milestones-heading">Two assigned projects inside this course.</h2><p>Each project unlocks only after its prerequisite modules are complete.</p></div></div><div className="course-milestone-grid">{projects.map((project, index) => <MinorProjectCard key={project.slug} course={course} project={project} status={statuses[index]} viewer={viewer} />)}</div></section>;
}

function MinorProjectCard({ course, project, status, viewer }: { course: ReturnType<typeof findCourse>; project: ReturnType<typeof courseProjectsFor>[number]; status: string; viewer: boolean }) {
  const locked = status === "LOCKED";
  const complete = status === "COMPLETED";
  const destination = `/learn/${course.slug}/project/${project.slug}`;
  const href = viewer ? destination : `/login?returnTo=${encodeURIComponent(destination)}`;
  const label = locked ? "Locked" : complete ? "Review project" : status === "AVAILABLE" ? "Start project" : "Continue project";
  return <article className={`minor-project-card minor-project-${status.toLowerCase()}`} aria-label={`Assigned project ${project.position}: ${project.title}`}><div className="minor-project-marker" aria-hidden="true">{locked ? <LockKeyhole size={18} /> : complete ? <Check size={18} /> : <FolderKanban size={18} />}</div><div className="minor-project-copy"><span className="eyebrow">ASSIGNED PROJECT {String(project.position).padStart(2, "0")} · AFTER MODULE {project.insertAfterModule}</span><h3>{project.title}</h3><p>{project.summary}</p><div className="minor-project-meta"><span>{project.difficulty}</span><span>{project.duration}</span><span>{project.skills.slice(0, 3).join(" · ")}</span></div>{locked ? <p className="minor-project-context"><LockKeyhole size={14} aria-hidden="true" /> Complete Modules 01–{project.insertAfterModule} to unlock.</p> : complete ? <p className="minor-project-context"><Check size={14} aria-hidden="true" /> Project complete.</p> : <p className="minor-project-context"><Target size={14} aria-hidden="true" /> Prerequisites complete. Apply the course skills.</p>}</div><Link className={`button ${locked ? "button-secondary" : ""}`} href={href}>{label} <ArrowRight size={16} aria-hidden="true" /></Link></article>;
}
